export const responseErrors = {
    bad_format: "bad_format",
    bad_format_email: "bad_format_email",
    bad_format_password: "bad_format_password",
    bad_format_email_password: "bad_format_email_password",
    unauthorized: "unauthorized",
    bad_credentials: "bad_credentials",
    forbidden: "forbidden",
    token_unauthorized: "token_unauthorized",
    already_logged_in: "already_logged_in",
    user_not_found: "user_not_found",
    email_already_exists: "email_already_exists",
    nickname_already_exists: "nickname_already_exists",
    name_already_exists: "name_already_exists",
    server_error: "server_error",
    not_verified: "not_verified",
    change_password: "change_password",
    already_verified: "already_verified",
    code_not_found: "code_not_found",
    bad_code: "bad_code",
    verification_code_already_sent: "verification_code_already_sent",
    slug_taken: "slug_taken",
    game_not_found: "game_not_found",
    team_not_found: "team_not_found",
    already_has_team: "already_has_team",
    already_in_team: "already_in_team",
    cant_remove_yourself: "cant_remove_yourself",
    player_not_found: "player_not_found",
    cant_leave_team_not_in: "cant_leave_team_not_in",
    cant_leave_your_team: "cant_leave_your_team",
};

export const responseSuccess = {
    success: "success",
    user_created: "user_created",
    login_success: "login_success",
    logout_success: "logout_success",
    user_found: "user_found",
    users_found: "users_found",
    user_updated: "user_updated",
    user_verified: "user_verified",
    verification_email_sent: "verification_email_sent",
    game_created: "game_created",
    games_found: "games_found",
    game_updated: "game_updated",
    teams_found: "teams_found",
    team_found: "team_found",
    team_created: "team_created",
    team_updated: "team_updated",
    team_deleted: "team_deleted",
    team_players_found: "team_players_found",
    team_left: "team_left",
};