export const responseErrors = {
    bad_format: "bad_format",
    unauthorized: "unauthorized",
    bad_credentials: "bad_credentials",
    forbidden: "forbidden",
    cookies_unauthorized: "cookies_unauthorized",
    already_logged_in: "already_logged_in",
    user_not_found: "user_not_found",
    email_already_exists: "email_already_exists",
    nickname_already_exists: "nickname_already_exists",
    server_error: "server_error",
    not_verified: "not_verified",
    change_password: "change_password",
    already_verified: "already_verified",
    code_not_found: "code_not_found",
    bad_code: "bad_code",
    verification_code_already_sent: "verification_code_already_sent",
};

export const responseSuccess = {
    success: "success",
    user_created: "user_created",
    login_success: "login_success",
    logout_success: "logout_success",
    user_found: "user_found",
    users_found: "users_found",
    user_updated: "user_updated",
    user_verified: "user_verified",
    verification_email_sent: "verification_email_sent",
};